### ISSUE TITLE
Published message content type is plain/text even if i use a JsonLayout to format log contents

### ISSUE THREAD

**Issue by SpoonPkup** [artdolya/Nlog.RabbitMQ#71]
Hello,
I have noticed an issue on content type of published message. Actually a JsonLayout is used for formatting the message and the configuration i  use is :
`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Off"
      internalLogToConsole="true"
      throwConfigExceptions="true">

    <extensions>
        <add assembly="NLog.Web.AspNetCore"/>
        <add assembly="Nlog.RabbitMQ.Target" />
    </extensions>

    <variable name="jsonlayout">
        <layout xsi:type="JsonLayout" EscapeForwardSlash="false" IncludeGdc="true" IncludeEventProperties="false" IncludeScopeProperties="true">
            <attribute name="Timestamp" layout ="${date:universalTime=true:format=yyyy-MM-ddTHH\:mmZ:culture=en-US}" />
            <attribute name="Level" layout="${level:upperCase=true}" />
            <attribute name="Hostname" layout ="${hostname}" />
            <attribute name="Environment" layout="${environment:APPLICATION_ENVIRONMENT}" />
            <attribute name="Message" layout="${message}" />
        </layout>
    </variable>

    <targets async="true">
        <target xsi:type="RabbitMQ"
                name="rabbit"
                exchange="e.logs"
                DeliveryMode="Persistent"
                layout="${jsonlayout}" />
        
        <target xsi:type="Console" 
                name="console" 
                layout="${jsonlayout}" />
    </targets>

    <rules>
        <logger name="System.*" finalMinLevel="Warn" />
        <logger name="Microsoft.*" finalMinLevel="Info" />
        <logger name="Microsoft.Hosting.Lifetime*" finalMinLevel="Info" />
        <logger name="*" minlevel="Trace" writeTo="rabbit" />
        <logger name="*" minlevel="Trace" writeTo="console" />
    </rules>
</nlog>`

When i log something in my application i use some scope properties to enrich the log content.

Regarding the source code of the RabbitMQTarget class, i noticed that a test is present to handle this case :
![image](https://github.com/artdolya/Nlog.RabbitMQ/assets/137197055/047c03a4-73b9-4c9c-bbb4-269536cabdca)

But after futher investigations i noticed that the type of my layout has changed from NLog.Layouts.JsonLayout, NLog to NLog.Targets.TargetWithContext+TargetWithContextLayout, NLog.

To solve this issue it will be nice : to fix the test used to determine if the layout is a json layout and/or provide a parameter to specify the content type using configuration.

**Comment by snakefoot** [comment]
Work-around is assign `UseJson = "true"`, but I think the `Layout is JsonLayout` should be removed and instead let the user control `ContentType`.

**Comment by snakefoot** [comment]
@SpoonPkup Created #72 to remove the guessing logic.

**Comment by SpoonPkup** [comment]
Thanks a lot!!
